import type { CategoriaCatalogo, ProductoIndustrial } from "@/datos/tipos-catalogo";

/**
 * Categorías industriales (propuesta del handoff / surtido GPar).
 * Confirmar nombres finales con el negocio.
 */
export const categoriasIndustriales: CategoriaCatalogo[] = [
  {
    id: "rodamientos",
    linea: "industrial",
    nombre: "Rodamientos",
    descripcion: "Rígidos de bolas, cónicos, de rodillos, de agujas y axiales.",
    publicada: true,
    subcategorias: ["Rígido de bolas", "Cónico", "De rodillos", "De agujas", "Axial"],
  },
  {
    id: "chumaceras",
    linea: "industrial",
    nombre: "Chumaceras",
    descripcion: "Soportes y unidades de rodamiento para ejes.",
    publicada: true,
  },
  {
    id: "correas",
    linea: "industrial",
    nombre: "Correas",
    descripcion: "Transmisión para equipos de producción.",
    publicada: true,
  },
  {
    id: "poleas",
    linea: "industrial",
    nombre: "Poleas",
    descripcion: "Sistemas de transmisión y acoplamiento.",
    publicada: true,
  },
  {
    id: "cadenas-pinones",
    linea: "industrial",
    nombre: "Cadenas y piñones",
    descripcion: "Transmisión por cadena para maquinaria.",
    publicada: true,
  },
  {
    id: "acoples",
    linea: "industrial",
    nombre: "Acoples",
    descripcion: "Acoplamientos y conexiones de ejes.",
    publicada: true,
  },
  {
    id: "sellos-mecanicos",
    linea: "industrial",
    nombre: "Sellos mecánicos",
    descripcion: "Sellado para bombas y equipos rotativos.",
    publicada: true,
  },
  {
    id: "estoperas-industriales",
    linea: "industrial",
    nombre: "Estoperas industriales",
    descripcion: "Retenes y estoperas para uso industrial.",
    publicada: true,
  },
  {
    id: "mangueras-industriales",
    linea: "industrial",
    nombre: "Mangueras industriales",
    descripcion: "Mangueras y conexiones para planta.",
    publicada: true,
  },
  {
    id: "motores-reductores",
    linea: "industrial",
    nombre: "Motores y reductores",
    descripcion: "Impulso y reducción para operaciones.",
    publicada: true,
  },
  {
    id: "ventiladores-axiales",
    linea: "industrial",
    nombre: "Ventiladores axiales",
    descripcion: "Ventilación industrial y extractores.",
    publicada: true,
  },
  {
    id: "bandas-transportadoras",
    linea: "industrial",
    nombre: "Bandas transportadoras",
    descripcion: "Bandas y componentes de transporte.",
    publicada: true,
  },
  {
    id: "guayas-cadenas-carga",
    linea: "industrial",
    nombre: "Guayas y cadenas de carga",
    descripcion: "Izaje y amarre industrial.",
    publicada: true,
  },
];

/**
 * Muestras tomadas del listado impreso (ficha: Código, Modelo, Descripción, Aplicación).
 * Temporal: validan la estructura. Completar con el resto del catálogo escaneado.
 * Nota: varias aplicaciones son vehiculares; confirmar si esta hoja va en industrial o carga pesada.
 */
export const productosIndustrialesMuestra: ProductoIndustrial[] = [
  {
    id: "ro-32004-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32004BS",
    modelo: null,
    nombre: "Rodamiento 32004 BS",
    descripcion: "32004 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32005-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32005BS",
    modelo: null,
    nombre: "Rodamiento 32005 BS",
    descripcion: "32005 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32006-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32006BS",
    modelo: null,
    nombre: "Rodamiento 32006 BS",
    descripcion: "32006 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32007-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32007BS",
    modelo: null,
    nombre: "Rodamiento 32007 BS",
    descripcion: "32007 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32008-jrrs-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32008JRRSB",
    modelo: null,
    nombre: "Rodamiento 32008 JRRS BS",
    descripcion: "32008 JRRS BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32009-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32009BS",
    modelo: null,
    nombre: "Rodamiento 32009 BS",
    descripcion: "32009 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32010-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32010BS",
    modelo: null,
    nombre: "Rodamiento 32010 BS",
    descripcion: "32010 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32011-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32011BS",
    modelo: null,
    nombre: "Rodamiento 32011 BS",
    descripcion: "32011 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32013-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32013BS",
    modelo: null,
    nombre: "Rodamiento 32013 BS",
    descripcion: "32013 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32014-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32014BS",
    modelo: null,
    nombre: "Rodamiento 32014 BS",
    descripcion: "32014 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32015-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32015BS",
    modelo: null,
    nombre: "Rodamiento 32015 BS",
    descripcion: "32015 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32016-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32016BS",
    modelo: null,
    nombre: "Rodamiento 32016 BS",
    descripcion: "32016 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32017-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32017BS",
    modelo: null,
    nombre: "Rodamiento 32017 BS",
    descripcion: "32017 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32018-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32018BS",
    modelo: null,
    nombre: "Rodamiento 32018 BS",
    descripcion: "32018 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32019-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32019BS",
    modelo: null,
    nombre: "Rodamiento 32019 BS",
    descripcion: "32019 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32020-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32020BS",
    modelo: null,
    nombre: "Rodamiento 32020 BS",
    descripcion: "32020 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32021-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32021BS",
    modelo: null,
    nombre: "Rodamiento 32021 BS",
    descripcion: "32021 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32022-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32022BS",
    modelo: null,
    nombre: "Rodamiento 32022 BS",
    descripcion: "32022 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32024-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32024BS",
    modelo: null,
    nombre: "Rodamiento 32024 BS",
    descripcion: "32024 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32026-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32026BS",
    modelo: null,
    nombre: "Rodamiento 32026 BS",
    descripcion: "32026 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32028-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32028BS",
    modelo: null,
    nombre: "Rodamiento 32028 BS",
    descripcion: "32028 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32207-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32207BS",
    modelo: null,
    nombre: "Rodamiento 32207 BS",
    descripcion: "32207 BS-",
    aplicacion: "NPR - RD/I -- SCANIA - REAR AXLE",
    imagen: null,
    destacado: true,
  },
  {
    id: "ro-32208-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32208BS",
    modelo: null,
    nombre: "Rodamiento 32208 BS",
    descripcion: "32208 BS-",
    aplicacion: "Caribe 83-89 / rueda trasera",
    imagen: null,
    destacado: true,
  },
  {
    id: "ro-32209-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32209BS",
    modelo: null,
    nombre: "Rodamiento 32209 BS",
    descripcion: "32209 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32210-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32210BS",
    modelo: null,
    nombre: "Rodamiento 32210 BS",
    descripcion: "32210 BS-",
    aplicacion: "NPR / Rueda del. Interna",
    imagen: null,
    destacado: true,
  },
  {
    id: "ro-32211-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32211BS",
    modelo: null,
    nombre: "Rodamiento 32211 BS",
    descripcion: "32211 BS-",
    aplicacion: "Autobus Ebro AV3500 / R.T. Interna",
    imagen: null,
  },
  {
    id: "ro-32212-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32212BS",
    modelo: null,
    nombre: "Rodamiento 32212 BS",
    descripcion: "32212 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32213-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32213BS",
    modelo: null,
    nombre: "Rodamiento 32213 BS",
    descripcion: "32213 BS-",
    aplicacion: "Encava / rueda trasera exterior",
    imagen: null,
    destacado: true,
  },
  {
    id: "ro-32214-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32214BS",
    modelo: null,
    nombre: "Rodamiento 32214 BS",
    descripcion: "32214 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32215-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32215BS",
    modelo: null,
    nombre: "Rodamiento 32215 BS",
    descripcion: "32215 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32216-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32216BS",
    modelo: null,
    nombre: "Rodamiento 32216 BS",
    descripcion: "32216 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32217-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32217BS",
    modelo: null,
    nombre: "Rodamiento 32217 BS",
    descripcion: "32217 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32218-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32218BS",
    modelo: null,
    nombre: "Rodamiento 32218 BS",
    descripcion: "32218 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32219-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32219BS",
    modelo: null,
    nombre: "Rodamiento 32219 BS",
    descripcion: "32219 BS-",
    aplicacion: "Camion Pegaso 1089C 2081 / Rueda Trasera",
    imagen: null,
    destacado: true,
  },
  {
    id: "ro-32220-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32220BS",
    modelo: null,
    nombre: "Rodamiento 32220 BS",
    descripcion: "32220 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32221-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32221BS",
    modelo: null,
    nombre: "Rodamiento 32221 BS",
    descripcion: "32221 BS-",
    aplicacion: "Camion Fiat 619-693 / Rueda Tras. Int.",
    imagen: null,
    destacado: true,
  },
  {
    id: "ro-32222-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32222BS",
    modelo: null,
    nombre: "Rodamiento 32222 BS",
    descripcion: "32222 BS-",
    aplicacion: null,
    imagen: null,
  },
  {
    id: "ro-32224-bs",
    linea: "industrial",
    categoriaId: "rodamientos",
    codigo: "RO32224BS",
    modelo: null,
    nombre: "Rodamiento 32224 BS",
    descripcion: "32224 BS-",
    aplicacion: null,
    imagen: null,
  },
];
